# Generated by Django 5.2.14 on 2026-05-29 01:18

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DissertationChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[("TEXT", "Text Chunk"), ("CODE", "Code Chunk")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("content", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                (
                    "code_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="submissions.submissionversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlagiarismMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("similarity_score", models.FloatField()),
                ("total_chunks_matched", models.PositiveIntegerField(default=0)),
                (
                    "matched_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matched_in",
                        to="submissions.submissionversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-similarity_score",),
            },
        ),
        migrations.CreateModel(
            name="PlagiarismChunkMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("similarity_score", models.FloatField()),
                (
                    "matched_chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archive_matches",
                        to="plagiarism.dissertationchunk",
                    ),
                ),
                (
                    "source_chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_matches",
                        to="plagiarism.dissertationchunk",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk_matches",
                        to="plagiarism.plagiarismmatch",
                    ),
                ),
            ],
            options={
                "ordering": ("-similarity_score",),
            },
        ),
        migrations.CreateModel(
            name="PlagiarismReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_score", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("flagged", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plagiarism_report",
                        to="submissions.submissionversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plagiarismmatch",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="plagiarism.plagiarismreport",
            ),
        ),
    ]
