# Generated by Django 5.2.14 on 2026-05-29 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=600, unique=True)),
                ("abstract", models.TextField()),
                ("keywords", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to="groups.projectgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to="dissertations/")),
                (
                    "code_file",
                    models.FileField(blank=True, null=True, upload_to="code/"),
                ),
                ("has_code", models.BooleanField(default=False)),
                ("extracted_text", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("PENDING_SUPERVISOR", "Pending Supervisor Review"),
                            ("SUPERVISOR_REJECTED", "Rejected by Supervisor"),
                            ("PENDING_DEAN", "Pending Dean Approval"),
                            ("DEAN_APPROVED", "Dean Approved"),
                            ("PUBLISHED", "Published"),
                            ("PROCESSING_FAILED", "Processing Failed"),
                            ("DEAN_REVOKED", "Revoked by Dean"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=30,
                    ),
                ),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="submissions.submission",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-version_number",),
                "unique_together": {("submission", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="SubmissionComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="submissions.submissionversion",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
