# Generated by Django 5.2.14 on 2026-05-29 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_CREATED", "User Created"),
                            ("USER_LOGIN", "User Login"),
                            ("USER_LOGOUT", "User Logout"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("PROFILE_UPDATED", "Profile Updated"),
                            ("USER_DEACTIVATED", "User Deactivated"),
                            ("FACULTY_CREATED", "Faculty Created"),
                            ("DEPARTMENT_CREATED", "Department Created"),
                            ("GROUP_CREATED", "Group Created"),
                            ("STUDENT_ADDED_TO_GROUP", "Student Added to Group"),
                            ("SUBMISSION_UPLOADED", "Submission Uploaded"),
                            ("SUBMISSION_RESUBMITTED", "Submission Resubmitted"),
                            ("COMMENT_ADDED", "Comment Added"),
                            ("COMMENT_RESOLVED", "Comment Resolved"),
                            ("PLAGIARISM_STARTED", "Plagiarism Started"),
                            ("PLAGIARISM_COMPLETED", "Plagiarism Completed"),
                            ("PLAGIARISM_FAILED", "Plagiarism Failed"),
                            ("PLAGIARISM_FLAGGED", "Plagiarism Flagged"),
                            ("SUPERVISOR_APPROVED", "Supervisor Approved"),
                            ("SUPERVISOR_REJECTED", "Supervisor Rejected"),
                            ("DEAN_APPROVED", "Dean Approved"),
                            ("DISSERTATION_PUBLISHED", "Dissertation Published"),
                            ("DISSERTATION_REVOKED", "Dissertation Revoked"),
                            ("REPROCESS_TRIGGERED", "Reprocess Triggered"),
                            ("GROUP_DEACTIVATED", "Group Deactivated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=500)),
                ("changes", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["actor"], name="audit_audit_actor_i_17b775_idx"
                    )
                ],
            },
        ),
    ]
