# Generated by Django 5.2.14 on 2026-05-29 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_CREATED", "Account Created"),
                            ("SUBMISSION_RECEIVED", "Submission Received"),
                            ("PLAGIARISM_REPORT_READY", "Plagiarism Report Ready"),
                            ("SUBMISSION_APPROVED", "Submission Approved"),
                            ("SUBMISSION_REJECTED", "Submission Rejected"),
                            ("DEAN_APPROVED", "Dean Approved"),
                            ("DISSERTATION_PUBLISHED", "Dissertation Published"),
                            ("DISSERTATION_REVOKED", "Dissertation Revoked"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email Only"),
                            ("IN_APP", "In-App Only"),
                            ("BOTH", "Email and In-App"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("body", models.TextField()),
                ("read", models.BooleanField(db_index=True, default=False)),
                (
                    "email_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
